# The Basics
dist: trusty
language: java
jdk:
- oraclejdk8

script: ./gradlew build
after_success:
  - '[[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" = "develop" ]] && ./gradlew uploadArchives'

# Ugh.
notifications:
  email: false
